// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_bkfrZq77P6ymq3OQOoINb73zJ9lJPOI',
    appId: '1:710442735711:web:8561926bad8fc3f2f923ea',
    messagingSenderId: '710442735711',
    projectId: 'ai-shopping-fdb19',
    authDomain: 'ai-shopping-fdb19.firebaseapp.com',
    storageBucket: 'ai-shopping-fdb19.firebasestorage.app',
    measurementId: 'G-NBYNG2QJX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQtzz-iX85VHlXumISUa_0CEYGXO0JaBU',
    appId: '1:710442735711:android:d3acd0fe9d521fe2f923ea',
    messagingSenderId: '710442735711',
    projectId: 'ai-shopping-fdb19',
    storageBucket: 'ai-shopping-fdb19.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_bkfrZq77P6ymq3OQOoINb73zJ9lJPOI',
    appId: '1:710442735711:web:ea45b66aa939384ef923ea',
    messagingSenderId: '710442735711',
    projectId: 'ai-shopping-fdb19',
    authDomain: 'ai-shopping-fdb19.firebaseapp.com',
    storageBucket: 'ai-shopping-fdb19.firebasestorage.app',
    measurementId: 'G-3HF4R4MNKV',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFJyrtHXwBtvEFSWj80GHYLwjIbgk1Wjw',
    appId: '1:710442735711:ios:7490d157888a725cf923ea',
    messagingSenderId: '710442735711',
    projectId: 'ai-shopping-fdb19',
    storageBucket: 'ai-shopping-fdb19.firebasestorage.app',
    iosClientId:
        '710442735711-8ij36keg7s16k3psuqomp4ee3ira0nei.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiShoppingAssistant',
  );
}
